language: generic
sudo: false

env:
    global:
    - BYOND_MAJOR="510"
    - BYOND_MINOR="1332"
    - NODE_VERSION="4"
    matrix:
    - DM_MAPFILE="tgstation2"
    - DM_MAPFILE="metastation"
    - DM_MAPFILE="ministation"
    - DM_MAPFILE="dreamstation"
    - DM_MAPFILE="birdstation"
    - DM_MAPFILE="efficiencystation"


cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}


addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip


install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $NODE_VERSION
  - npm install -g gulp-cli
  - pip install --user PyYaml -q
  - pip install --user beautifulsoup4 -q

before_script:
  - cd tgui && npm install && cd ..
  - chmod +x ./install-byond.sh
  - ./install-byond.sh
  - shopt -s globstar

script:
  - (! grep 'step_[xy]' _maps/**/*.dmm)
  - md5sum -c - <<< "49bc6b1b9ed56c83cceb6674bd97cb34 *html/changelogs/example.yml"
  - tools/check_filedirs.sh tgstation.dme
  - cd tgui && gulp && cd ..
  - python tools/ss13_genchangelog.py html/changelog.html html/changelogs
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh -M${DM_MAPFILE} tgstation.dme
